export const SERVICOS_DATA = [
    {
        id: 1,
        photoId: 'FOTOFREELANCER1',
        imageFreelancer: require('@/assets/img/FOTOFREELANCER1.png'),
        nome: 'Andrey Silva',
        profissao: 'Desenvolvedor Web',
        descricao: 'Criação de landing pages e sistemas web responsivos. Especialista em React e Node.js com entrega rápida e qualidade garantida.',
        avaliacao: 4.8,
        contactId: '1',
    },
    {
        id: 2,
        photoId: 'FOTOFREELANCER',
        imageFreelancer: require('@/assets/img/FOTOFREELANCER.png'),
        nome: 'Geovana Oliveira',
        profissao: 'Designer Gráfico',
        descricao: 'Identidade visual completa, logotipos e materiais para redes sociais. Transformo sua ideia em uma marca memorável e profissional.',
        avaliacao: 5.0,
        contactId: '11',
    },
    {
        id: 3,
        photoId: 'MULHER1',
        imageFreelancer: require('@/assets/img/MULHER1.jpg'),
        nome: 'Maria Santos',
        profissao: 'Redatora',
        descricao: 'Produção de conteúdo para blogs, redes sociais e e-mail marketing. Textos otimizados para SEO com linguagem clara e persuasiva.',
        avaliacao: 4.6,
        contactId: '2',
    },
    {
        id: 4,
        photoId: 'HOMEM2',
        imageFreelancer: require('@/assets/img/HOMEM2.jpg'),
        nome: 'João Pedro',
        profissao: 'Fotógrafo',
        descricao: 'Ensaios para produtos, eventos e retratos profissionais. Edição inclusa com entrega das fotos em até 48 horas após a sessão.',
        avaliacao: 4.4,
        contactId: '3',
    },
    {
        id: 5,
        photoId: 'HOMEM3',
        imageFreelancer: require('@/assets/img/HOMEM3.jpg'),
        nome: 'Carlos Eduardo',
        profissao: 'Dev Mobile',
        descricao: 'Desenvolvimento de aplicativos iOS e Android com React Native. Do wireframe ao deploy na loja em tempo recorde e com suporte pós-entrega.',
        avaliacao: 4.9,
        contactId: '12',
    },
    {
        id: 6,
        photoId: 'MULHER2',
        imageFreelancer: require('@/assets/img/MULHER2.jpg'),
        nome: 'Ana Beatriz',
        profissao: 'Social Media',
        descricao: 'Gestão completa de redes sociais com estratégia de conteúdo, agendamento de posts e relatórios mensais de desempenho.',
        avaliacao: 4.7,
        contactId: '13',
    },
    {
        id: 7,
        photoId: 'HOMEM4',
        imageFreelancer: require('@/assets/img/HOMEM4.jpg'),
        nome: 'Lucas Mendes',
        profissao: 'Consultor SEO',
        descricao: 'Auditoria e otimização de sites para buscadores. Estratégia de palavras-chave e link building com resultados mensuráveis em 60 dias.',
        avaliacao: 4.3,
        contactId: '14',
    },
    {
        id: 8,
        photoId: 'HOMEM5',
        imageFreelancer: require('@/assets/img/HOMEM5.jpg'),
        nome: 'Roberto Alves',
        profissao: 'Videomaker',
        descricao: 'Produção e edição de vídeos para YouTube, Instagram e campanhas publicitárias. Motion graphics e trilha sonora inclusos.',
        avaliacao: 4.5,
        contactId: '15',
    },
    {
        id: 9,
        photoId: 'HOMEM6',
        imageFreelancer: require('@/assets/img/HOMEM6.jpg'),
        nome: 'Michel Oliveira',
        profissao: 'UI/UX Designer',
        descricao: 'Prototipagem e design de interfaces digitais centradas no usuário. Entrego arquivo Figma completo com guia de estilo e componentes.',
        avaliacao: 4.5,
        contactId: '16',
    },
    {
        id: 10,
        photoId: 'MULHER3',
        imageFreelancer: require('@/assets/img/MULHER3.jpg'),
        nome: 'Ana Carolina',
        profissao: 'Dev Mobile',
        descricao: 'Aplicativos mobile com foco em performance e design intuitivo. Especialista em Flutter com publicação nas stores e manutenção contínua.',
        avaliacao: 4.8,
        contactId: '17',
    },
    {
        id: 11,
        photoId: 'FOTOFREELANCER2',
        imageFreelancer: require('@/assets/img/FOTOFREELANCER2.jpg'),
        nome: 'Pedro Lima',
        profissao: 'Produtor Musical',
        descricao: 'Composição, arranjo e produção musical para jingles, trilhas e podcasts. Gravação profissional em home studio com mixagem e masterização.',
        avaliacao: 4.6,
        contactId: '18',
    },
];
